### ISSUE TITLE
Incompatibility with Mobile Devices

### ISSUE THREAD

**Issue by gczh** [smubia/smubia#4]
![image](https://user-images.githubusercontent.com/1908934/31166245-a6dbe878-a920-11e7-90ad-8521c049178f.png)

Currently, our site is incompatible with mobile devices smaller than an iPhone 6S Plus. This issue probably has something to do with the way the Foundation classes for columns are declared. Very possibly, it involves using media queries in SCSS (use the foundation helpers)

It would require you to install the tooling (gulp, jekyll, etc) in order to test.

- [ ] The fix should be compatible on all modern, majority smartphone devices and their respective resolutions.
- [ ] The fix should be reflected in ALL other templates as well.
- [ ] The fix does not break the Web view.

**Comment by lmhs** [comment]
Hi @gczh!
Please check this pull request: #5 
I have changed menu items display from table-cell to inline-block, so that they can move to the next line instead of breaking the layout on small screens:
![screen shot 2017-10-08 at 15 44 21](https://user-images.githubusercontent.com/363187/31316923-f4414dc0-ac3f-11e7-8450-cec45ec917c6.png)
